@baseUrl = http://localhost:3000
@token = ""

### Login API
POST {{baseUrl}}/api/v1/auth/login
Content-Type: application/json

{
  "email": "thanhtrung2205200@gmail.com",
  "password": "trung2205"
}

### Logout API
POST {{baseUrl}}/api/v1/auth/logout
Content-Type: application/json


### GET ACCOUNT
GET {{baseUrl}}/api/v1/auth/account
Content-Type: application/json

