@baseUrl = http://localhost:3000
@token = ""

# GET list company pagination
POST  {{baseUrl}}/api/v1/candidate
Content-Type: application/json

{
  "userId": "686cb5b802a159956bb2a370",
  "name": "Tăng Thành Trung",
  "birthday": null,
  "phone": "0773735100",
  "industry": "Infomation Technology",
  "skills": [
    "JavaScript",
    "TypeScript",
    "ReactJS",
    "NodeJS"
  ],
  "avatar": "",
  "designation": "Backend Developer",
  "location": "63/2 Tân Hóa Phường Phú Lâm",
  "hourlyRate": null,
  "description": "Tôi là một lập trình viên backend với hơn 3 năm kinh nghiệm trong việc phát triển các ứng dụng web và dịch vụ RESTful. Tôi có kỹ năng vững chắc trong việc sử dụng Node.js, Express, và MongoDB để xây dựng các hệ thống hiệu quả và mở rộng được. Tôi đam mê công nghệ và luôn cập nhật những xu hướng mới nhất trong lĩnh vực phát triển phần mềm.",
  "experience": "",
  "currentSalary": "",
  "expectSalary": "",
  "gender": "male",
  "language": [
    "Tiếng Việt",
    "English"
  ],
  "educationLevel": "Đại học",
  "socialMedias": []
}
